/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Folder */
        post: operations["open_folder_api_folder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entries */
        get: operations["entries_api_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate */
        post: operations["rate_api_rate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Species */
        post: operations["confirm_species_api_species_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/species/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Species Model */
        get: operations["species_model_api_species_model_get"];
        put?: never;
        /** Download Species Model */
        post: operations["download_species_model_api_species_model_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/species/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Species Names */
        get: operations["species_names_api_species_names_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/{idx}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thumb */
        get: operations["thumb_api_image__idx__thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/{idx}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full
         * @description The embedded full-resolution JPEG, raw bytes, no re-encode.
         */
        get: operations["full_api_image__idx__full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AFInfo */
        AFInfo: {
            /** Lattice */
            lattice: boolean;
            /** Orientation */
            orientation: number;
            /** N Points */
            n_points: number;
            /** Display Points */
            display_points: components["schemas"]["AFPoint"][];
        };
        /** AFPoint */
        AFPoint: {
            /** Cx */
            cx: number;
            /** Cy */
            cy: number;
            /** W */
            w: number;
            /** H */
            h: number;
            /** In Focus */
            in_focus: boolean;
            /** Selected */
            selected: boolean;
        };
        /** BirdBox */
        BirdBox: {
            /** X0 */
            x0: number;
            /** Y0 */
            y0: number;
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
            /** Confidence */
            confidence: number;
        };
        /** Entry */
        Entry: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Orientation */
            orientation: number;
            /** Burst */
            burst: number | null;
            /** Burst Size */
            burst_size: number;
            /** Rank */
            rank: number | null;
            /** Metrics */
            metrics: {
                [key: string]: number | null;
            } | null;
            eye: components["schemas"]["Eye"] | null;
            /** Eye Used */
            eye_used: boolean;
            /** Birds */
            birds: components["schemas"]["BirdBox"][] | null;
            af: components["schemas"]["AFInfo"] | null;
            /** Species */
            species: components["schemas"]["SpeciesPrediction"][] | null;
            /** Species User */
            species_user: string | null;
            /** Shot Time */
            shot_time: string | null;
            /** User Rating */
            user_rating: number | null;
            /** Rejected */
            rejected: boolean;
        };
        /** ExportResponse */
        ExportResponse: {
            /** Written */
            written: number;
            /** Skipped Foreign */
            skipped_foreign: number;
        };
        /** Eye */
        Eye: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Confidence */
            confidence: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OpenFolderRequest */
        OpenFolderRequest: {
            /** Path */
            path: string;
            /**
             * Detect
             * @default true
             */
            detect: boolean;
            /**
             * Eye
             * @default true
             */
            eye: boolean;
            /**
             * Species
             * @default true
             */
            species: boolean;
            /**
             * Gap Seconds
             * @default 3
             */
            gap_seconds: number;
            /**
             * Metric
             * @default brenner
             */
            metric: string;
        };
        /** OpenFolderResponse */
        OpenFolderResponse: {
            /** Status */
            status: string;
            /** Folder */
            folder: string;
        };
        /** RateRequest */
        RateRequest: {
            /** Id */
            id: number;
            /** Rating */
            rating?: number | null;
            /** Rejected */
            rejected?: boolean | null;
        };
        /** SpeciesModelStatus */
        SpeciesModelStatus: {
            /** Present */
            present: boolean;
            /** Downloading */
            downloading: boolean;
            /** Done Bytes */
            done_bytes: number;
            /** Total Bytes */
            total_bytes: number;
            /** Error */
            error: string | null;
        };
        /** SpeciesPrediction */
        SpeciesPrediction: {
            /** Common */
            common: string | null;
            /** Scientific */
            scientific: string;
            /** Family */
            family: string | null;
            /** Confidence */
            confidence: number;
        };
        /** SpeciesRequest */
        SpeciesRequest: {
            /** Burst */
            burst: number;
            /** Common */
            common: string | null;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Status */
            status: string;
            /** Error */
            error: string | null;
            /** Count */
            count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    open_folder_api_folder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenFolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    entries_api_entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"][];
                };
            };
        };
    };
    rate_api_rate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_species_api_species_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeciesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    species_model_api_species_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesModelStatus"];
                };
            };
        };
    };
    download_species_model_api_species_model_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesModelStatus"];
                };
            };
        };
    };
    species_names_api_species_names_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    export_api_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    thumb_api_image__idx__thumb_get: {
        parameters: {
            query?: {
                w?: number;
            };
            header?: never;
            path: {
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    full_api_image__idx__full_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
